import type { Metadata } from 'next';
import { Toaster } from 'sonner';
import './globals.css';
import Sidebar from '@/components/common/sidebar';
import { authSession } from '@/lib/auth-utils';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await authSession();

  return (
    <html lang="en" className="antialiased">
      <body className="bg-neutral-100 text-neutral-900 font-sans flex">
        {session?.user.id && <Sidebar />}
        <div className="w-full min-w-dvw overflow-hidden">{children}</div>
        <Toaster position="bottom-right" richColors />
      </body>
    </html>
  );
}
